/*
a)  Угол* бифуркации
b)	Угол* отклонения внутренней сонной артерии (ВСА). англ. ICA
c)	Угол* отклонения наружней сонной артерии (НСА). англ. ECA
d)	Диаметр** общей сонной артерии (ОСА). англ. CCA
e)	Диаметр** луковицы (максимальный). англ. ? aortic bulb
f)	Диаметр** внутренней сонной артерии (ВСА). англ. ICA
*/

export type tablePatientsRowProps = {
    id: number,
    externalId: string,
    description?: string | null,
    angle_bifurcation?: number | null,
    angle_BCA?: number | null,
    angle_HCA?: number | null,
    diameter_OCA?: number | null,
    diameter_bulb?: number | null,
    diameter_ВСА?: number | null,
    calc_delta_OCA_bulb?: number | null, 
    calc_delta_bulb_ВСА?: number | null,
    calc_delta_OCA_ВСА?: number | null,
    calc_ratio_bulb_ВСА?: number | null,
    classifier?: string | null,
    treatment?: string | null,
    doctor?: string | null,
}

export let patientsRows: tablePatientsRowProps[] = [
    {
        id: 125123, 
        externalId: "74er152", 
        description: "Lorem ipsum dolor 1", 
        angle_bifurcation: 12,
        angle_BCA: 56,
        angle_HCA: 33,
        diameter_OCA: 23,
        diameter_bulb: null,
        diameter_ВСА: null,
        calc_delta_OCA_bulb: 523, 
        classifier: "Quis nulla",
        treatment: "Ut enim ad minim veniam",
        doctor: "Петров И.В.",
    },
    {
        id: 125124, 
        externalId: "16er182", 
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        angle_bifurcation: 32,
        angle_BCA: 44,
        angle_HCA: 23,
        diameter_OCA: 17,
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Иванов А.Г.",
    },
    {
        id: 125125, 
        externalId: "76er352", 
        description: "Lorem ipsum dolor 2",
        angle_bifurcation: 51,
        classifier: "Quis nulla",
        treatment: "Quis autem vel eum Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.",
        doctor: "Кузнецов М.В.",
    },
    {
        id: 125126, 
        externalId: "74er122", 
        description: "Lorem ipsum dolor 45", 
        angle_bifurcation: null,
        angle_BCA: null,
        angle_HCA: null,
        diameter_OCA: null,
        diameter_bulb: null,
        diameter_ВСА: null,
        classifier: "Quis nulla",
        treatment: "Ut enim ad minim veniam",
        doctor: "Жванецкий М.М.",
    },
    {
        id: 125127, 
        externalId: "16er133", 
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        angle_bifurcation: 45,
        angle_BCA: 12,
        angle_HCA: 25,
        diameter_OCA: 19,
        diameter_bulb: 22,
        diameter_ВСА: 8,
        calc_delta_OCA_bulb: 232584, 
        calc_delta_bulb_ВСА: 123123,
        calc_delta_OCA_ВСА: 879879,
        calc_ratio_bulb_ВСА: 12333,
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Яровицина З.Г.",
    },
    {
        id: 125128, 
        externalId: "76er354", 
        description: "Lorem ipsum dolor 12",
        angle_bifurcation: 33,
        angle_BCA: 22,
        angle_HCA: 11,
        diameter_OCA: 5,
        diameter_bulb: 9,
        diameter_ВСА: 18,
        classifier: "Quis nulla",
        treatment: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat",
        doctor: "Григорьев М.В.",
    },
    {
        id: 125129, 
        externalId: "74er882", 
        description: "Lorem ipsum dolor 16",
        angle_bifurcation: 11,
        angle_BCA: 9,
        angle_HCA: 8,
        diameter_OCA: 19,
        diameter_bulb: 19,
        diameter_ВСА: 1,
        classifier: "Quis nulla",
        treatment: "Ut enim ad minim veniam",
        doctor: "Мусагалиев И.В.",
    },
    {
        id: 125130, 
        externalId: "16er180", 
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.",
        angle_bifurcation: 45,
        angle_BCA: 12,
        angle_HCA: 25,
        diameter_OCA: 19,
        diameter_bulb: 22,
        diameter_ВСА: 8,
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Приходько А.Г.",
    },
    {
        id: 125131, 
        externalId: "76er352", 
        description: "Lorem ipsum dolor 256",
        angle_bifurcation: 57,
        angle_BCA: 2,
        angle_HCA: 5,
        diameter_OCA: 9,
        diameter_bulb: 22,
        diameter_ВСА: 9,
        classifier: "Quis nulla",
        treatment: "Quis autem vel eum iure reprehenderit",
        doctor: "Абрамов М.В.",
    },
    {
        id: 125132, 
        externalId: "74er152", 
        description: "Lorem ipsum dolor 1", 
        angle_bifurcation: 125,
        angle_BCA: 112,
        angle_HCA: 35,
        diameter_OCA: 29,
        diameter_bulb: 12,
        diameter_ВСА: 11,
        classifier: "Quis nulla",
        treatment: "Ut enim ad minim veniam",
        doctor: "Петров И.В.",
    },
    {
        id: 125133, 
        externalId: "16er182", 
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Иванов А.Г.",
    },
    {
        id: 125134, 
        externalId: "76er352", 
        description: "Lorem ipsum dolor 2", 
        classifier: "Quis nulla",
        treatment: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
        doctor: "Васнецов М.В.",
    },
    {
        id: 125135, 
        externalId: "16er111", 
        description: "Quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Галкин А.Г.",
    },
    {
        id: 125136, 
        externalId: "76er334", 
        description: "Lorem ipsum dolor 2", 
        angle_bifurcation: 9,
        angle_BCA: 12,
        angle_HCA: 15,
        diameter_OCA: 29,
        diameter_bulb: 32,
        diameter_ВСА: 14,
        classifier: "Quis nulla",
        treatment: "Reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
        doctor: "Пугачева М.В.",
    },
];
