export type tablePatientsRowProps = {
    id: number,
    externalId: string,
    description?: string | null,
    parameters?: string | null,
    calc_parameters?: string | null,
    classifier?: string | null,
    treatment?: string | null,
    doctor?: string | null,
}

export let patientRows: tablePatientsRowProps[] = [
    {
        id: 125123, 
        externalId: "74er152", 
        description: "Lorem ipsum dolor 1", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Ut enim ad minim veniam",
        doctor: "Петров И.В.",
    },
    {
        id: 125124, 
        externalId: "16er182", 
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Иванов А.Г.",
    },
    {
        id: 125125, 
        externalId: "76er352", 
        description: "Lorem ipsum dolor 2", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.",
        doctor: "Кузнецов М.В.",
    },
    {
        id: 125126, 
        externalId: "74er122", 
        description: "Lorem ipsum dolor 45", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Ut enim ad minim veniam",
        doctor: "Жванецкий М.М.",
    },
    {
        id: 125127, 
        externalId: "16er133", 
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Яровицина З.Г.",
    },
    {
        id: 125128, 
        externalId: "76er354", 
        description: "Lorem ipsum dolor 12", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat",
        doctor: "Григорьев М.В.",
    },
    {
        id: 125129, 
        externalId: "74er882", 
        description: "Lorem ipsum dolor 16", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Ut enim ad minim veniam",
        doctor: "Мусагалиев И.В.",
    },
    {
        id: 125130, 
        externalId: "16er180", 
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Приходько А.Г.",
    },
    {
        id: 125131, 
        externalId: "76er352", 
        description: "Lorem ipsum dolor 256", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Quis autem vel eum iure reprehenderit",
        doctor: "Абрамов М.В.",
    },
    {
        id: 125132, 
        externalId: "74er152", 
        description: "Lorem ipsum dolor 1", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Ut enim ad minim veniam",
        doctor: "Петров И.В.",
    },
    {
        id: 125133, 
        externalId: "16er182", 
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Иванов А.Г.",
    },
    {
        id: 125134, 
        externalId: "76er352", 
        description: "Lorem ipsum dolor 2", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
        doctor: "Васнецов М.В.",
    },
    {
        id: 125135, 
        externalId: "16er111", 
        description: "Quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Duis aute irure dolor in reprehenderit",
        doctor: "Галкин А.Г.",
    },
    {
        id: 125136, 
        externalId: "76er334", 
        description: "Lorem ipsum dolor 2", 
        parameters: "23/45/34/23°/45°/65°/кругл.",
        calc_parameters: "45/32/24/1,32",
        classifier: "Quis nulla",
        treatment: "Reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
        doctor: "Пугачева М.В.",
    },
];
